[[constraint]]
  name = "github.com/heptio/workgroup"
  version = "0.8.0-beta.1"

[[constraint]]
  branch = "master"
  name = "golang.org/x/crypto"

[prune]
  go-tests = true
  unused-packages = true
